language: rust
rust: nightly

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y alien
    - sudo alien nasm-2.11.08-1.x86_64.rpm
    - sudo dpkg -i nasm_2.11.08-2_amd64.deb

script: make x86
