language: rust
rust: nightly

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y alien grub2 xorriso
    - wget http://cz.archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu-system-x86_2.0.0+dfsg-2ubuntu1.13_amd64.deb
    - wget http://www.nasm.us/pub/nasm/releasebuilds/2.11.08/linux/nasm-2.11.08-1.x86_64.rpm
    - sudo dpkg -i qemu-system-x86_2.0.0+dfsg-2ubuntu1.13_amd64.deb
    - sudo alien nasm-2.11.08-1.x86_64.rpm
    - sudo dpkg -i nasm_2.11.08-2_amd64.deb

script: make x86-check
