language: rust
rust: nightly

before_install:
    - wget http://archive.ubuntu.com/ubuntu/pool/main/n/nasm/nasm_2.11.06-1really2.11.05-1_amd64.deb
    - sudo dpkg -i nasm_2.11.06-1really2.11.05-1_amd64.deb

script: make x86
